### ISSUE TITLE
Paletă de culoare pentru site

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#10]
Trebuie să găsim o paletă de culori potrivită pentru site. Ar trebui să conțină câteva culori ( ~5 ) care să fie folosite pentru elementele de design. 

Una din ele trebuie să fie cea/cele din logo (albastru deschis). 

Un site: http://www.colourlovers.com/web/palettes

**Comment by IoanAlexandru** [comment]
Am gasit ceva interesant ca paleta: https://color.adobe.com/QuickDesign-color-theme-6558488/

**Comment by ieugen** [comment]
E faină paleta. Deschisă și frumoasă. Am o rugăminte. Lasă-mă pe mine să închid issueurile când consider că sunt gata. Dă doar un comentariu pe ele că ai terminat.

**Comment by IoanAlexandru** [comment]
Am inteles. Asa o sa fac pe viitor.
