### ISSUE TITLE
Lista de servicii

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#2]
Următoarea bucată importantă de conținut este lista de servicii pe care le face Quickdesign. Oamenii viziteză situl pentru că sunt interesați să facă unul din servicii. Se vor uita la preț și nu numai. 

Scrie un document text care să conțină serviciile și caracteristicile acestora. Poți copia lista de servicii din imaginile trimise. 

Când o să facem designul sitului, vom copia conținutul în pagină (paote în mai multe locuri chiar) și îl vom structura corespunzător. 

La fel, nu scrie HTML. Vrem doar conținutul disponibil. O listă lungă de servicii. cu descriere, preț, categoria din care face parte, toată informația pe care o poți obține din imagini și textul disponibil.

**Comment by IoanAlexandru** [comment]
Am rezolvat. Am urcat documentul pe dropbox.
