### ISSUE TITLE
Structura sitului

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#3]
Ca să facem structura sitului trebuie să analizăm conținutul și să ne gândim cum s-ar comporta utlizatorul când accesează situl. 

Am vrea să-i oferim tot ce are nevoie cu cât mai puține clicuri, dar în același timp să nu-i dăm prea multă informație ca să-l confuzăm. 

Situl este unul simplu și vom avea o structură simplă, dar aș vrea să o discutăm. Vom face o conferință pentru asta.

**Comment by IoanAlexandru** [comment]
Am inchis issue-ul pentru ca am urcat mock-ul pe dropbox.
