### ISSUE TITLE
probleme pe site

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#4]
Salut, 

Ai făcut ceva modificări și situl nu mai merge cum trebuie. 
http://ieugen.github.io/quickdesign.ro/

**Comment by IoanAlexandru** [comment]
Am adaugat variabila baseurl si dupa niste trial and error am facut in asa fel incat toate elementele sa fie legate corect intre ele. M-a indus in eroare o vreme faptul ca informatiile pe github se updatau putin mai greu dar i-am dat de cap in cele din urma.
