### ISSUE TITLE
Mock pentru site

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#5]
Salut, 

Ținând cont de Actori (Vizitator), de nevoile sale (use case-uri: a se informa despre produse, program, abonare la newsletter, contact ) și de Conținut, crează un design (mockup) de interfață care să răspună la aceste chestiuni. 

Are legătură cu #3

**Comment by ieugen** [comment]
Am urcat diagrama de use-case-uri: https://www.dropbox.com/s/y9g9n0h3bonvvh9/diagrama-use-case-quickdesign.png?dl=0 la documente. Designul ar trebui să răspundă la toate cazurile de acolo.

**Comment by IoanAlexandru** [comment]
Am facut mock-ul, ramane sa ii fac poza si sa o pun pe dropbox, cel mai probabil maine dimineata.

**Comment by IoanAlexandru** [comment]
Am urcat mock-ul pe dropbox: https://www.dropbox.com/home/quickdesign-docs?preview=mockup+quickdesign.jpg. Cand ai timp sa vorbim despre el da-mi un semn.
