### ISSUE TITLE
Pagina Facebook

### ISSUE THREAD

**Issue by IoanAlexandru** [ieugen/quickdesign.ro#6]
Am terminat segmentul cu testimoniale mai devreme, am adaugat date simple precum nume, varsta, ocupatie si mesaj pentru fiecare testimonial. Pe langa asta am adaugat o imagine care deocamdata e identica pentru fiecare testimonial si am modificat putin setarile slider-ului. Cand ai timp, lasa-mi mesaj cu ce e de facut in continuare.

**Comment by ieugen** [comment]
Arată chiar bine. Bravo. Te rog să te ocupi de pagina de Facebook. 'Quickdesign.ro' este liber. Fă un cont și urcă datele de contact, adresă, hartă, numere de telefon.

**Comment by IoanAlexandru** [comment]
Pagina de facebook e terminata, o poti gasi la https://www.facebook.com/pages/Quickdesignro/1397844930232295?fref=ts . Daca trebuie modificat ceva fac asta inainte de a schimba administratorul la livrare.

**Comment by ieugen** [comment]
Pagina de Facebook trebuie să fie gata de producție. Pune adresa către situl original și scoate materialele demo pe care le-ai pus. Este publică, chiar dacă nu intră acum nimeni pe ea și trebuie șă fie cum trebuie.

**Comment by IoanAlexandru** [comment]
Cand spui materiale demo te referi la postarile legate de servicii?

**Comment by ieugen** [comment]
Da.

**Comment by IoanAlexandru** [comment]
Rezolvat. O sa las pe mail userul si parola.
