### ISSUE TITLE
Mailchimp Account

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#7]
Următoarea treabă este să faci un cont la mailchimp.com pentru quickkdesign. Fă-l cu datele lor cât se poate de mult să facem migrarea ușor după (la fel și la Facebook).

**Comment by IoanAlexandru** [comment]
Am terminat si cu contul de Maichimp. Username-ul este : quickdesignro iar Parola este : Parola_mea1

**Comment by ieugen** [comment]
Gihub issues este public. Nu mai pune informații senzitive aici.
