### ISSUE TITLE
Conținutul pe site

### ISSUE THREAD

**Issue by ieugen** [ieugen/quickdesign.ro#9]
M-am uitat pe mockup și este ok. 
Câteva note (te rog să faci issuuri din ele): 
- Orarul ar merge trecut și în banner undeva, discret dar vizibil. 
- Mențiunea cu programul de vară merge afișată cu JavaScript, doar dacă timpul în calculator este în perioada respectivă. 

Pentru că nu avem mult conținut o să păstrăm o singură pagină pentru tot situl, cu fiecare categorie listată acolo. După ce facem asta și ne ocupăm și de aspectul sitului facem o prezentare și vedem ce mai modificăm sau livrăm și gata.

**Comment by IoanAlexandru** [comment]
Am urcat noua versiune a site-ului, nu par sa fie erori. Am terminat si cu MailChimp si cu GoogleAnalytics. Singura problema ar fi ca tine ceva ca persoana ce se aboneaza la newsletter sa primeasca mailul prin care confirma ca asta vrea.
